update and game speed and while ensuring dosent go out of bound
lovebaihezi/dinosaur-game pull request #45
Opened 2024-12-01 14:16 UTC by zprjd

2024-12-01 14:23 UTC, lovebaihezi requested changes

2024-12-01 14:23 UTC, lovebaihezi commented on .vscode/launch.json
> +{
Remove vscode related files

2024-12-01 14:23 UTC, lovebaihezi commented on crates/game/src/tree.rs
> +    color::Color, math::{Vec2, Vec3}, prelude::{default, Commands, Query, Res, ResMut, Transform}, sprite::{Sprite, SpriteBundle}, time::{Time, Virtual}, ui::update, window::Window
Run Cargo fmt before commit

2024-12-01 14:23 UTC, lovebaihezi commented on crates/game/src/tree.rs
> +            SPEED_INCREMENT = SPEED_INCREMENT.saturating_add(SPEED_INCREMENT);
Speed should not use static mut, consider store it inside component or using bevy resources

2024-12-01 14:23 UTC, lovebaihezi commented on crates/game/src/tree.rs
> +        println!("tree_move_animation Modified speed: {}  MAX_GAME_SPEED {}", status.speed, MAX_GAME_SPEED);
using function from log, not directly using println!

2024-12-01 15:51 UTC, lovebaihezi commented
Run `cargo clippy --fix` to fix the error from the CI/CD

2024-12-02 15:22 UTC, zprjd commented
> cargo clippy --fix

done

2024-12-02 16:41 UTC, lovebaihezi approved these changes

2024-12-02 16:43 UTC, merged